language: go
go:
  - 1.7.x
  - master

# Go has this weird thing where it forces you to execute tests for the vendored libraries.
# This is a problem for us because the postgres driver pq has tests that depend on having an
# active postgres up. This is a bit of a hack around it and this command is reccommended for
# running tests while developing 
script: go test -v $(go list ./... | grep -v /vendor/)

deploy:
  provider: heroku
  api_key:
    secure: Bh5aAdue5PpBCMEEjCd4JwpbPiEI41fmsYIdByoxUm1N56SvC+OKTqDKS79jVQT9TqDgjOyQtA+k1zsf71X9HxSpvCHwArfSK0iPNhEoWfaR1cHn1VAxUqMy/q2SOD37iPTZVBOdLZslgzUUaVw8MskQDT0h0U1C7emub9l3pAqVTmAJ3hjDSVGjjs5BtI8HQ8fMWOvEdKazdTPeDX1K9r/0kDhSWdFYNovB+MBhMOvzJvm7/hLLQpWkAyKl5Yij56o2avF26ZlRWWKvChX365f/EjEmnYPWOagFyMroJdqwCKF8OTpy9TcR2wFWRW6Wq4LaCOMtjAA85Z/B763Dol8m4ZfOEeGh+MRRPP7VZdRfo/oNqYKwaWDP1NynjtupIB4Ji+YC3kvhjpjR9sUnBZ89YJhbm0iN+b8Li2gXpmnOM3EyrPFb3sCEiGx8zXdQmEx6qOjZDJdy46xI2izaUxosOyllDfGcXKu7zVRzGFy1U5Zkeeu/M7kxPZ6TvUX5z3687WiQkLcJzB0o9u6/Fxf2kyHDZdLehqASM5RosALsFMddd/SsqvLERDSSXq4/tBQseeA9zsEzg2Y6/OhjIzxk7PuLoC4oL3TYwVgJJPUsaR5zICJ22H4svsSuLQy25M7xtPSvIzpdjnWGufMV2hRHHHwQjEcwGND/WfNkDBk=
  app: linkletter
  on: 
    branch: master
    condition: $TRAVIS_GO_VERSION = 1.7.x

