language: go

go:
    - 1.7.x
    - master

deploy:
    provider: heroku
    api_key:
    secure: "q1tA89ZosLw26wWXMbPc+SzBwLbdypqURULU/XVwOQ9c1RJLGFEaBoKYJJ5CkZxe1kRWzLPue1qitp8xaL9yrpQgwqLBS2l0GUPP05m4W4APnYuaL0D4MTAhOZiqcapWGAz15+stXb+jNeB6OtzKXkstM8oNGAMwt+nJmcsx03XlcMCeJLkM8L2Qw4CiVONG8rmBTJQneEUXpHLatmR+wm6LidfjrbeIQ2hXd7WKBXCIB4kLl1YoE4S0c3DQ8MiLDpiTCgjRHk0RELb/QiKR68EWedUBknNCshmVBxJGOlVQnwgI54m+ax7koQ69mdBNBavSBAG5daEHMTtEp+wfgrwGapwkQygZ4trNjwYPnYEgptZ2cbOUQAl3MgMtPCjwfDZqOoVoZL4RFJXD/a7021NPh8+mBHI3NedlXt4DjIxOAfI7bLhgEpKaBVnx1nRBXYK/Nu1ujwKltkm1F6IAKPb/hfwdpjLJGQRcbQXpyrI2suxhPBu48owc7fjOwM6bY+w1tJdqTP1vRtcNcHJrQTVqOvmoQr/1d/LdEfipuamOcdNoqBcZ3tqH7qMXziwL9pL5h4rVAh/OtPumg3l2pzxBdT4edjqS7R7hBSFt4caWoQ+j8882Z7cmTVbd6WEUGpR4g8st4jrlzdyquJUVirHLU+B/7AcWYodQzP3PJ2I="
    app: linkletter
    on: master
