#!/usr/bin/env bash

RED='\033[0;31m'
NC='\033[0m'

GODEP=$GOPATH/bin/godep

if ! ls $GODEP > /dev/null ; then
    go get github.com/tools/godep
fi

$GODEP save -t

if ! ./`dirname $0`/test ; then
    echo
    echo -e "${RED}There are errors in your tests that should be resolved before committing.${NC}"
fi
